name: 3-2

on:
  pull_request:
  workflow_dispatch:

jobs:
  event-condition:
    runs-on: ubuntu-latest

    steps:
      - name: pull_request
        if: ${{github.event_name == 'pull_request'}}
        run: echo "run on pull_request"

      - name: workflow_dispatch
        if: ${{github.event_name == 'workflow_dispatch'}}
        run: echo "run on workflow_dispatch"